### ISSUE TITLE
Logging Messages

### ISSUE THREAD

**Issue by etridenour** [ibm-watson-iot/iot-nodejs#117]
appClient.log.setLevel('info') logs info to the console. Is there a way to grab this information, possibly in JSON format?

**Comment by durera** [comment]
We use https://www.npmjs.com/package/loglevel for logging, which [supports plugins](https://www.npmjs.com/package/loglevel#writing-plugins), a plugin could be written to achieve this.

This plugin may be of interest,  https://github.com/kutuluk/loglevel-plugin-remote .. even if your goal is to make the logs available locally rather than remote, you could configure it to publish to something listening locally in your application.
