### ISSUE TITLE
Are there any news about the new npm package?

### ISSUE THREAD

**Issue by nicosquare** [ibm-watson-iot/iot-nodejs#151]
Hi everyone,

First of all thanks for the efforts you are putting to stabilize this package. I am wondering if there are plans to finally publish it to npm as I couldn't find any news about it in the issues. I also want to know if there is a place where I can access the documentation of ibmiotf (besides the information that appears at npm).

Thanks in advance for the answer.

**Comment by prabhu66** [comment]
Hi,

when i am trying to install **npm install @wiotp/sdk --save** I am getting error. Anyways to resolve this error. See the below error.

C:\Users\ibm\Downloads\iot-nodejs-master\iot-nodejs-master>npm i @wiotp/sdk
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "@wiotp/sdk" under a package
npm ERR! also called "@wiotp/sdk". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ibm\AppData\Roaming\npm-cache\_logs\2020-06-12T14_44_54_538Z-debug.log


hope to hear from you soon @nicosquare

**Comment by durera** [comment]
@tomklapiscak Tom, could you take a look at updating the package hosted on NPM?  If not I'll try to find some time next week to do so.

**Comment by tomklapiscak** [comment]
@nicosquare @durera Latest code from `master` has been published to npm as version `0.7.7`: https://www.npmjs.com/package/@wiotp/sdk/v/0.7.7.

@prabhu66 I think that is happening because you trying to install `@wiotp/sdk` as a dependency of itself (based on the pathname of `iot-nodejs-master` shown in your logs).

If you want to **rebuild** the library to include changes you have made, inside that directory, you need to execute `npm i` (to download the library's dependencies) then `npm run build` (which will output the built version of the library under `dist`).

If you are trying to use the library from within another project, run `npm -i @wiotp/sdk --save` from within that other project's root folder (i.e. where its `package.json` is located).

**Comment by tomklapiscak** [comment]
@nicosquare documentation for the platform is available here: https://www.ibm.com/support/knowledgecenter/SSQP8H/iot/developing/iot_platform.html
