### ISSUE TITLE
Pass the content of CA Certificate instead the path in order to connect a device

### ISSUE THREAD

**Issue by CAIOFCP** [ibm-watson-iot/iot-nodejs#82]

**Comment by CAIOFCP** [comment]
@amitmangalvedkar Do you have any plans to close this issue?

**Comment by amitmangalvedkar** [comment]
@CAIOFCP : This is assigned to Lokesh.  
@Lokesh-K-Haralakatta : As discussed, could you please document the changes that you have done?

**Comment by Lokesh-K-Haralakatta** [comment]
The code already supports read certificates contents to be passed while connecting to WIoTP. To pass the read certificates contents, one has to use **read-certs: true** in the configuration file. Basically, this was added to make the device connections using node-red to get the certificates contents and use in with this library and being used as internal flag. One has to pass the certificates contents in proper json format, otherwise json unexpected error is thrown. Here is sample configuration file to directly provide certificate contents:

{
        "org": "9y92nw",
        "domain": "internetofthings.ibmcloud.com",
        "type": "elevator",
        "id": "android",
        "auth-method": "token",
        "auth-token": "password",
        "use-client-certs": true,
        **"read-certs": true,**
        "client-ca": "Certificate Contents",
        "client-cert": "Certificate Contents",
        "client-key": "Certificate Contents"
}

**Comment by CAIOFCP** [comment]
Thanks @Lokesh-K-Haralakatta and @amitmangalvedkar
